use_frameworks!

platform :ios, '9.0'

target 'MYTestLib_Example' do
  pod 'MYTestLib', :path => 'https://github.com/zzg4321/helloworldlib.git'

  target 'MYTestLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
